In [2]:
import os

In [3]:
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'jupyterApp.ipynb',
 'learningNumpy.ipynb',
 'learnPandas.ipynb',
 'newsmallgray.png',
 'scrape.ipynb',
 'smallgray.png',
 'supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx',
 'Testings.ipynb',
 'Untitled.ipynb',
 'Untitled1.ipynb']

In [4]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [5]:
import numpy

In [6]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
type(n)

numpy.ndarray

In [8]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [9]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
import pandas

In [11]:
m=numpy.asarray([(123,12,123,12,33),(),()])

In [12]:
print(m)

[(123, 12, 123, 12, 33) () ()]


In [13]:
m.reshape(3,1)

array([[(123, 12, 123, 12, 33)],
       [()],
       [()]], dtype=object)

In [14]:
m=m.reshape(3,1)

In [15]:
m

array([[(123, 12, 123, 12, 33)],
       [()],
       [()]], dtype=object)

In [16]:
print(m)

[[(123, 12, 123, 12, 33)]
 [()]
 [()]]


In [17]:
m=m.reshape(1,3)

In [18]:
m

array([[(123, 12, 123, 12, 33), (), ()]], dtype=object)

In [19]:
print(m)

[[(123, 12, 123, 12, 33) () ()]]


In [20]:
import cv2

In [21]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
im_g=cv2.imread("smallgray.png",0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [23]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [24]:
a=[1,2,3]

In [25]:
a[0:2]

[1, 2]

In [26]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [28]:
im_g.shape

(3, 5)

In [29]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [30]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [31]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [51]:
ims=numpy.hstack((im_g,im_g,im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [54]:
lst=numpy.hsplit(ims,3)
print(lst)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [69]:
for i in lst:
    print("new:\n",i)

new:
 [[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
new:
 [[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
new:
 [[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [71]:
print(lst[0])

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [72]:
for n in lst[0]:
    for t in n:
        print(t)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
